package com.runner;
import java.util.concurrent.TimeUnit;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.openqa.selenium.WebDriver;
import com.base.Base_Class2;
import com.helper.File_Reader_Manager;
import sdp2.Page_Object_Manger2;
public class Test_Runner2  extends Base_Class2{
	public static WebDriver driver=browser("chrome");
	public static Page_Object_Manger2 pom =new Page_Object_Manger2(driver);
	public static Logger  log= Logger.getLogger(Test_Runner2.class);
	public static void main(String[] args) throws Throwable {
		PropertyConfigurator.configure("log4j.properties");
		log.info("browser launched");
		String url = File_Reader_Manager.getInstanceFRM().getInstanceCR().getUrl();
url(url);
log.info("url launched");
implictywait(6000, TimeUnit.SECONDS);
pom.getInstancel().getName();
String user = particular_data("C:\\Users\\surya\\eclipse-workspace\\Maven_Project2\\excel\\testcase for adactin1.xlsx", 1, 5);
input(pom.getInstancel().getName(), user);
pom.getInstancel().getPass();
String pass = particular_data("C:\\Users\\surya\\eclipse-workspace\\Maven_Project2\\excel\\testcase for adactin1.xlsx", 2, 5);
input(pom.getInstancel().getPass(), pass);
pom.getInstancel().getLogin();
clickOnElement(pom.getInstancel().getLogin());
log.info("login successfully");
pom.getInstanced().getLocation();
selectbyindex(pom.getInstanced().getLocation(), 2);
pom.getInstanced().getHotel();
selectbyindex(pom.getInstanced().getHotel(), 3);
pom.getInstanced().getType();
selectbyindex(pom.getInstanced().getType(), 1);
pom.getInstanced().getNo_of_room();
selectbyindex(pom.getInstanced().getNo_of_room(), 4);
pom.getInstanced().getCheckin();
clear(pom.getInstanced().getCheckin());
String in = particular_data("C:\\Users\\surya\\eclipse-workspace\\Maven_Project2\\excel\\testcase for adactin1.xlsx", 5, 5);
input(pom.getInstanced().getCheckin(), in);
pom.getInstanced().getCheckout();
clear(pom.getInstanced().getCheckout());
String out = particular_data("C:\\Users\\surya\\eclipse-workspace\\Maven_Project2\\excel\\testcase for adactin1.xlsx", 6, 5);
input(pom.getInstanced().getCheckout(), out);
pom.getInstanced().getAdult_room();
selectbyindex(pom.getInstanced().getAdult_room(), 3);
pom.getInstanced().getSumbit();
performclick(pom.getInstanced().getSumbit());
log.info("successfully details uploaded");
pom.getInstances().getBox();
performclick(pom.getInstances().getBox());
pom.getInstances().getLetsgo();
performclick(pom.getInstances().getLetsgo());
pom.getInstancep().getFirst();
String first = particular_data("C:\\Users\\surya\\eclipse-workspace\\Maven_Project2\\excel\\testcase for adactin1.xlsx", 8, 5);
input(pom.getInstancep().getFirst(), first);
pom.getInstancep().getLast();
String last = particular_data("C:\\Users\\surya\\eclipse-workspace\\Maven_Project2\\excel\\testcase for adactin1.xlsx", 9, 5);
input(pom.getInstancep().getLast(), last);
pom.getInstancep().getAddress();
String address = particular_data("C:\\Users\\surya\\eclipse-workspace\\Maven_Project2\\excel\\testcase for adactin1.xlsx", 10, 5);
input(pom.getInstancep().getAddress(), address);
pom.getInstancep().getCardno();
String getcardno = File_Reader_Manager.getInstanceFRM().getInstanceCR().getcardno();
input(pom.getInstancep().getCardno(), getcardno);
pom.getInstancep().getCardtype();
selectbyindex(pom.getInstancep().getCardtype(), 2);
pom.getInstancep().getMonth();
selectbyindex(pom.getInstancep().getMonth(), 8);
pom.getInstancep().getYear();
selectbyindex(pom.getInstancep().getYear(), 11);
pom.getInstancep().getCcv();
String ccv = File_Reader_Manager.getInstanceFRM().getInstanceCR().getccv();
;input(pom.getInstancep().getCcv(), ccv);
pom.getInstancep().getBook();
performclick(pom.getInstancep().getBook());
sleep();
pom.getInstancee().getEnd();
scroll(pom.getInstancee().getEnd());
scrolluplittle();
screenshot();
log.info("successfully booked");
	}

}
